Repository VeryGoodOpenSource/very_good_infinite_list, pull requests merged in 2021-02, with the labels that each got.

#5 docs: fix typo in README
  README.md
Labels: documentation

#7 feat: Add reverse property and inject scrollController
  example/lib/main.dart
  lib/very_good_infinite_list.dart
  test/very_good_infinite_list_test.dart
Labels: enhancement

#8 chore: v0.2.0
  CHANGELOG.md
  pubspec.yaml
Labels: chore

#9 feat: add padding api to InfiniteList
  CHANGELOG.md
  example/lib/main.dart
  lib/very_good_infinite_list.dart
  pubspec.yaml
  test/very_good_infinite_list_test.dart
Labels: enhancement
